package hibernateconfig.hbm;
// Generated Jan 23, 2012 6:57:48 AM by Hibernate Tools 3.4.0.CR1



/**
 * VbmsUser generated by hbm2java
 */
public class VbmsUser  implements java.io.Serializable {


    

	private Integer userId;
     private String userName;
     private String userLogin;
     private String userPassword;
     private String userMenu;
     private String status;
     private String accessType;

    public VbmsUser() {
    }

    public VbmsUser(String userName, String userLogin, String userPassword, String userMenu, String status, String accessType) {
       this.userName = userName;
       this.userLogin = userLogin;
       this.userPassword = userPassword;
       this.userMenu = userMenu;
       this.status = status;
       this.accessType = accessType;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserMenu() {
        return this.userMenu;
    }
    
    public void setUserMenu(String userMenu) {
        this.userMenu = userMenu;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
   

    public String getAccessType() {
		return accessType;
	}

	public void setAccessType(String accessType) {
		this.accessType = accessType;
	}

}


