package com.vbms.domain;
// Generated Jan 23, 2012 6:57:48 AM by Hibernate Tools 3.4.0.CR1



/**
 * VbmsVoter generated by hbm2java
 */
public class VbmsVoterDTO  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int voterid;
     private String votername;
     private String cardnumber;
     private String address;
     private String constituency;
     private String boothnumber;
     private String ward;
     private String gender;
     private String age;
     private String qualification;
     private String maritalstatus;
     private String children;
     private String childrenqualification;
     private String houseincome;
     private String housetype;
     private String rentyears;
     private String fathername;

    public VbmsVoterDTO() {
    }

	
    public VbmsVoterDTO(int voterid, String votername, String cardnumber, String constituency, String boothnumber, String ward, String gender, String age) {
        this.voterid = voterid;
        this.votername = votername;
        this.cardnumber = cardnumber;
        this.constituency = constituency;
        this.boothnumber = boothnumber;
        this.ward = ward;
        this.gender = gender;
        this.age = age;
    }
    public VbmsVoterDTO(int voterid, String votername, String cardnumber, String address, String constituency, String boothnumber, String ward, String gender, String age, String qualification, String maritalstatus, String children, String childrenqualification, String houseincome, String housetype, String rentyears, String fathername) {
       this.voterid = voterid;
       this.votername = votername;
       this.cardnumber = cardnumber;
       this.address = address;
       this.constituency = constituency;
       this.boothnumber = boothnumber;
       this.ward = ward;
       this.gender = gender;
       this.age = age;
       this.qualification = qualification;
       this.maritalstatus = maritalstatus;
       this.children = children;
       this.childrenqualification = childrenqualification;
       this.houseincome = houseincome;
       this.housetype = housetype;
       this.rentyears = rentyears;
       this.fathername = fathername;
    }
   
    public int getVoterid() {
        return this.voterid;
    }
    
    public void setVoterid(int voterid) {
        this.voterid = voterid;
    }
    public String getVotername() {
        return this.votername;
    }
    
    public void setVotername(String votername) {
        this.votername = votername;
    }
    public String getCardnumber() {
        return this.cardnumber;
    }
    
    public void setCardnumber(String cardnumber) {
        this.cardnumber = cardnumber;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getConstituency() {
        return this.constituency;
    }
    
    public void setConstituency(String constituency) {
        this.constituency = constituency;
    }
    public String getBoothnumber() {
        return this.boothnumber;
    }
    
    public void setBoothnumber(String boothnumber) {
        this.boothnumber = boothnumber;
    }
    public String getWard() {
        return this.ward;
    }
    
    public void setWard(String ward) {
        this.ward = ward;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public String getMaritalstatus() {
        return this.maritalstatus;
    }
    
    public void setMaritalstatus(String maritalstatus) {
        this.maritalstatus = maritalstatus;
    }
    public String getChildren() {
        return this.children;
    }
    
    public void setChildren(String children) {
        this.children = children;
    }
    public String getChildrenqualification() {
        return this.childrenqualification;
    }
    
    public void setChildrenqualification(String childrenqualification) {
        this.childrenqualification = childrenqualification;
    }
    public String getHouseincome() {
        return this.houseincome;
    }
    
    public void setHouseincome(String houseincome) {
        this.houseincome = houseincome;
    }
    public String getHousetype() {
        return this.housetype;
    }
    
    public void setHousetype(String housetype) {
        this.housetype = housetype;
    }
    public String getRentyears() {
        return this.rentyears;
    }
    
    public void setRentyears(String rentyears) {
        this.rentyears = rentyears;
    }
    public String getFathername() {
        return this.fathername;
    }
    
    public void setFathername(String fathername) {
        this.fathername = fathername;
    }




}


