package com.vbms.domain;

 
// Generated Jan 16, 2012 11:26:26 PM by Hibernate Tools 3.4.0.CR1



/**
 * VbmsUser generated by hbm2java
 */
public class VbmsUserDTO  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer userId;
     private String userName;
     private String userLogin;
     private String userPassword;
     private String userMenu;
     private String status;
     private String accessType;
     				 
    public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	 

	public String getAccessType() {
		return accessType;
	}

	public void setAccessType(String accessType) {
		this.accessType = accessType;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public VbmsUserDTO() {
    }

    public VbmsUserDTO(String userName, String userLogin, String userPassword, String userMenu) {
       this.userName = userName;
       this.userLogin = userLogin;
       this.userPassword = userPassword;
       this.userMenu = userMenu;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(String userLogin) {
        this.userLogin = userLogin;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserMenu() {
        return this.userMenu;
    }
    
    public void setUserMenu(String userMenu) {
        this.userMenu = userMenu;
    }




}


